---
- name: Ping my hosts
  ansible.builtin.ping:
- name: Check Minikube's status.
  command: minikube status
  register: minikube_status
  changed_when: false
  ignore_errors: true
- debug:
    msg: "Minikube status minikube_status"
- name: Start Minikube if it's not running.
  command: minikube start --vm-driver docker
  when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"